npc:
    x: 12.5
    y: 112
    z: 63.5
maps:
    tower:
        start:
            x: 20
            y: 109
            z: 188
        loc1:
            x: 3
            y: 121
            z: 171
        loc2:
            x: 5
            y: 121
            z: 173
    village:
        start:
            x: 70
            y: 100
            z: 257
        loc1:
            x: 92
            y: 106
            z: 243
        loc2:
            x: 94
            y: 106
            z: 245