npc:
    x: 81.5
    y: 65
    z: 26.5
maps:
    red:
        start:
            x: 85
            y: 66
            z: 25
        loc1:
            x: 58
            y: 68
            z: 14
        loc2:
            x: 60
            y: 68
            z: 16
    blue:
        start:
            x: 86
            y: 65
            z: 27
        loc1:
            x: 118
            y: 72
            z: 40
        loc2:
            x: 120
            y: 72
            z: 42
    green:
        start:
            x: 85
            y: 66
            z: 31
        loc1:
            x: 52
            y: 81
            z: 44
        loc2:
            x: 54
            y: 81
            z: 46
    yellow:
        start:
            x: 86
            y: 65
            z: 29
        loc1:
            x: 95
            y: 75
            z: 62
        loc2:
            x: 97
            y: 75
            z: 64